# .github/workflows/main.yml
name: Main Workflow

on:
  push:
    branches: [ "development", "main" ]
  pull_request:
    branches: [ "development", "main" ]
  workflow_dispatch:

jobs:
  codeql:
    uses: ./.github/workflows/2.codeql.yml
    with:
      language: 'csharp'
      dotnet-version: '10.0.x'
    permissions:
      security-events: write
      contents: read

  snyk:
    uses: ./.github/workflows/3.snyk.yml
    with:
      dotnet-version: '10.0.x'
    secrets: inherit

  build:
    needs: [codeql, snyk]
    uses: ./.github/workflows/4.build.yml
    with:
      dotnet-version: '10.0.x'

  publish:
    needs: build
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    uses: ./.github/workflows/5.publish.yml
    with:
      dotnet-version: '10.0.x'
    secrets: inherit
    permissions:
      contents: write
      packages: write